### ISSUE TITLE
Tole je mogoče za preverit, vem da je neko pravilo, da se najprej napiše občno ime pred lastnim – torej "Vpis z **računom Microsoft**" namesto "Vpis z **Microsoftovim računom**" ...

### ISSUE THREAD

**Issue by DmgCoder** [SCVApp/SCVAppFrontend#9]
Tole je mogoče za preverit, vem da je neko pravilo, da se najprej napiše občno ime pred lastnim – torej "Vpis z **računom Microsoft**" namesto "Vpis z **Microsoftovim računom**" ...

_Originally posted by @tzuntar in https://github.com/SCVApp/SCVAppFrontend/pull/8#discussion_r901069555_

**Comment by BlazOsredkar** [comment]
![Screenshot 2022-06-19 at 12 45 02](https://user-images.githubusercontent.com/91890538/174477142-b86f275f-77e5-443d-b9c8-03c9edadf12d.png)
Kolikor vidim na spletu, je Microsoft pred računom

LP
